'\" t
.\"     Title: dmbot
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2024-10-13
.\"    Manual: User Commands
.\"    Source: DMBOT
.\"  Language: English
.\"
.TH "DMBOT" "1" "2024-10-13" "DMBOT" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmbot \- XMPP chat bot for remote control of sensor nodes
.SH "SYNOPSIS"
.sp
\fBdmbot\fP \-\-help
.sp
\fBdmbot\fP \-\-version
.sp
\fBdmbot\fP \-\-\fBnode\fP \fIid\fP \-\-\fBjid\fP \fIjid\fP \-\-\fBpassword\fP \fIpassword\fP \-\-\fBhost\fP \fIhost\fP
[\-\-\fBport\fP \fIport\fP] [\-\-\fBtls\fP] [\-\-\fBlogger\fP \fIname\fP] [\-\-\fBdebug\fP] [\-\-\fBverbose\fP]
.sp
\fBdmbot\fP \-\-\fBconfig\fP \fIfile\fP [\-\-\fBname\fP \fIname\fP]
.SH "DESCRIPTION"
.sp
This program is an XMPP bot that accepts commands via chat. Clients must be
granted access first by adding them to the roster of the bot account. The bot
denies requests from clients whose JID is not included in the roster. The XMPP
resource is automatically set to the name of the bot instance.
.sp
All commands start with prefix \f(CR!\fP. For an overview, send chat command \f(CR!help\fP
to the bot. The following commands are supported:
.sp
!beats
.RS 4
Return current time of the sensor node in Swatch Internet Time.
.RE
.sp
!date
.RS 4
Return date and time of the sensor node in ISO 8601.
.RE
.sp
!help
.RS 4
Return help text.
.RE
.sp
!jid
.RS 4
Return full JID of bot.
.RE
.sp
!log <level> "<message>"
.RS 4
Send log message of given level to logger. The argument \f(CRlevel\fP must be a
valid log level name or numeric log level. The argument \f(CRmessage\fP must be in
quotes.
.RE
.sp
!node
.RS 4
Return node id of bot.
.RE
.sp
!poke
.RS 4
Return status message if bot is online.
.RE
.sp
!reconnect
.RS 4
Reconnect bot and update local roster list.
.RE
.sp
!roster
.RS 4
Return list of authorised users from the roster.
.RE
.sp
!uname
.RS 4
Return name and version of the operating system.
.RE
.sp
!uptime
.RS 4
Return uptime of the operating system
.RE
.sp
!version
.RS 4
Return bot version.
.RE
.sp
Update the list of authorised users by adding them to the roster of the bot and
sending command \f(CR!reconnect\fP afterwards. The bot will update the local roster
after the reconnection.
.sp
Passing the XMPP credentials via the command\-line arguments \f(CR\-\-jid\fP and
\f(CR\-\-password\fP is insecure on multi\-user operating systems and only recommended
for testing.
.SH "OPTIONS"
.sp
\fB\-\-config\fP, \fB\-c\fP \fIfile\fP
.RS 4
Path to Lua\-based configuration file.
.RE
.sp
\fB\-\-debug\fP, \fB\-D\fP
.RS 4
Forward logs messages of level \f(CRLL_DEBUG\fP via IPC (if logger is set).
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Output available command\-line arguments and quit.
.RE
.sp
\fB\-\-host\fP, \fB\-H\fP \fIhost\fP
.RS 4
Domain of XMPP server.
.RE
.sp
\fB\-\-jid\fP, \fB\-J\fP \fIuser\fP
.RS 4
Jabber id (JID) of the form \f(CRuser@example.com\fP.
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of logger. If set, sends logs to \fIdmlogger(1)\fP process of given name.
.RE
.sp
\fB\-\-name\fP, \fB\-n\fP \fIname\fP
.RS 4
Name of instance, XMPP resource, and table in given configuration file
(default is \f(CRdmbot\fP).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Sensor node id.
.RE
.sp
\fB\-\-password\fP, \fB\-P\fP \fIpassword\fP
.RS 4
JID password. Be aware that passing the credentials via command\-line
arguments is insecure and only recommended for testing.
.RE
.sp
\fB\-\-port\fP, \fB\-q\fP \fIport\fP
.RS 4
Port of XMPP server. The default port is 5222.
.RE
.sp
\fB\-\-reconnect\fP, \fB\-R\fP
.RS 4
Reconnect on error.
.RE
.sp
\fB\-\-tls\fP, \fB\-E\fP
.RS 4
Force TLS encryption.
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log messages to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Output version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Program executed without errors.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Program execution failed.
.RE
.SH "EXAMPLE"
.sp
Connect with JID \f(CRbot@example.com\fP to an XMPP server on port 5223 and wait for
commands:
.sp
.if n .RS 4
.nf
.fam C
$ dmbot \-\-node dummy\-node \-\-jid bot@example.com \-\-password secret \(rs
  \-\-host example.com \-\-port 5223 \-\-tls \-\-verbose
.fam
.fi
.if n .RE
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2024 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel