'\" t
.\"     Title: dmexport
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.21
.\"      Date: 2024-03-06
.\"    Manual: User Commands
.\"    Source: DMEXPORT
.\"  Language: English
.\"
.TH "DMEXPORT" "1" "2024-03-06" "DMEXPORT" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmexport \- exports records from database to file
.SH "SYNOPSIS"
.sp
\fBdmexport\fP \-\-help
.sp
\fBdmexport\fP \-\-version
.sp
\fBdmexport\fP \-\-\fBdatabase\fP \fIfile\fP \-\-\fBtype\fP \fItype\fP \-\-\fBformat\fP \fIformat\fP
\-\-\fBnode\fP \fIid\fP [\-\-\fBoutput\fP \fIfile\fP] [\-\-\fBsensor\fP \fIid\fP] [\-\-\fBtarget\fP \fIid\fP]
[\-\-\fBresponse\fP \fIname\fP] [\-\-\fBfrom\fP \fItimestamp\fP] [\-\-\fBto\fP \fItimestamp\fP] [\-\-\fBheader\fP]
[\-\-\fBseparator\fP \fIchar\fP]
.SH "DESCRIPTION"
.sp
The \fBdmexport\fP program writes logs, nodes, sensors, targets, and observations
from database to file, in ASCII block, CSV, JSON, or JSON Lines format. The
ASCII block data format is only available for X/Y data points.
.sp
The types data point, log, and observation require a given sensor id, target id,
and time range in ISO 8601 format.
.sp
If no output file is given, the data is printed to standard output. The
output file will be overwritten if it already exists. If no records are found,
an empty file will be created.
.SH "OPTIONS"
.sp
\fB\-\-database\fP, \fB\-d\fP \fIfile\fP
.RS 4
Path of the SQLite database (required).
.RE
.sp
\fB\-\-format\fP, \fB\-f\fP [block|csv|json|jsonl]
.RS 4
Output file format, either ASCII block, CSV, JSON, JSON Lines (required).
Only data points can be exported in block format.
.RE
.sp
\fB\-\-from\fP, \fB\-B\fP \fItimestamp\fP
.RS 4
Start of time range in ISO 8601 (required for types \f(CRdb\fP, \f(CRlog\fP, \f(CRobserv\fP).
.RE
.sp
\fB\-\-header\fP, \fB\-H\fP
.RS 4
Enable CSV header.
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Output available command\-line arguments and quit.
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Node id (required).
.RE
.sp
\fB\-\-output\fP, \fB\-o\fP \fIfile\fP
.RS 4
Path of output file. Empty or \f(CR\-\fP for standard output.
.RE
.sp
\fB\-\-response\fP, \fB\-R\fP \fIname\fP
.RS 4
Response name (required for type \f(CRdp\fP).
.RE
.sp
\fB\-\-sensor\fP, \fB\-S\fP \fIid\fP
.RS 4
Sensor id (required for types \f(CRdp\fP and \f(CRobserv\fP).
.RE
.sp
\fB\-\-separator\fP, \fB\-s\fP \fIchar\fP
.RS 4
Single character used as separator instead of comma.
.RE
.sp
\fB\-\-target\fP, \fB\-T\fP \fIid\fP
.RS 4
Target id (required for type \f(CRdp\fP and \f(CRobserv\fP).
.RE
.sp
\fB\-\-to\fP, \fB\-E\fP \fItimestamp\fP
.RS 4
End of time range in ISO 8601 (required for types \f(CRdp\fP, \f(CRlog\fP, and \f(CRobserv\fP).
.RE
.sp
\fB\-\-type\fP, \fB\-t\fP [beat|dp|log|node|observ|sensor|target]
.RS 4
Type of records to export (required).
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Output version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Records have been exported.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Export of records failed.
.RE
.SH "EXAMPLE"
.sp
Export log messages from database to JSON file:
.sp
.if n .RS 4
.nf
.fam C
$ dmexport \-\-database log.sqlite \-\-type log \-\-format json \-\-node dummy\-node \(rs
  \-\-from 2020\-01\-01 \-\-to 2025\-01\-01 \-\-output /tmp/log.json
.fam
.fi
.if n .RE
.sp
Export observations from database to CSV file:
.sp
.if n .RS 4
.nf
.fam C
$ dmexport \-\-database observ.sqlite \-\-type observ \-\-format csv \-\-node dummy\-node \(rs
  \-\-sensor dummy\-sensor \-\-target dummy\-target \-\-from 2020\-01\-01 \-\-to 2025\-01\-01 \(rs
  \-\-output /tmp/observ.csv
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fIdmimport(1)\fP
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2024 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel