'\" t
.\"     Title: dmgrc
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-08-15
.\"    Manual: User Commands
.\"    Source: DMGRC
.\"  Language: English
.\"
.TH "DMGRC" "1" "2025-08-15" "DMGRC" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmgrc \- creates log messages from Leica GeoCOM return codes
.SH "SYNOPSIS"
.sp
\fBdmgrc\fP \-\-help
.sp
\fBdmgrc\fP \-\-version
.sp
\fBdmgrc\fP [\-\-\fBnode\fP \fIid\fP] [\-\-\fBlevel\fP \fIlevel\fP] [\-\-\fBresponse\fP \fIname\fP]
[\-\-\fBname\fP \fIname\fP] [\-\-\fBlogger\fP \fIname\fP] [\-\-\fBdebug\fP] [\-\-\fBverbose\fP]
.sp
\fBdmgrc\fP \-\-\fBconfig\fP \fIfile\fP [\-\-\fBname\fP \fIname\fP]
.SH "DESCRIPTION"
.sp
The \fBdmgrc\fP program creates log messages from Leica GeoCOM return codes.
Observations received by POSIX message queue are searched for a GeoCOM return
code (GRC) response. If the code does not equal \f(CRGRC_OK\fP, a log message is sent
to the configured logger instance.
.sp
By default, observation responses of name \f(CRgrc\fP are verified. For each GeoCOM
error code, a custom log level may be specified in the configuration file.
Otherwise, the default log level is used instead.
.SH "OPTIONS"
.sp
\fB\-\-config\fP, \fB\-c\fP \fIfile\fP
.RS 4
File path to the optional configuration file.
.RE
.sp
\fB\-\-debug\fP, \fB\-D\fP
.RS 4
Forward logs messages of level \f(CRLL_DEBUG\fP via IPC (if logger is set).
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Print available command\-line arguments and quit.
.RE
.sp
\fB\-\-level\fP, \fB\-L\fP \fIlevel\fP
.RS 4
Default log level of return codes other than \f(CRGRC_OK\fP (\f(CRLL_WARNING\fP by
default). The argument may be an integer or name string.
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of \fIdmlogger(1)\fP process to send logs to.
.RE
.sp
\fB\-\-name\fP, \fB\-n\fP \fIname\fP
.RS 4
Name of program instance and configuration (\f(CRdmgrc\fP by default).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Node id.
.RE
.sp
\fB\-\-response\fP, \fB\-R\fP \fIname\fP
.RS 4
Response name of the GeoCOM return code (\f(CRgrc\fP by default).
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log messages to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Print version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Process terminated without errors.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Process failed.
.RE
.SH "EXAMPLE"
.sp
A configuration file is not required, but allows to specifiy the log level of
certain GeoCOM return codes. In the following example configuration, the default
log level for all return codes other than \f(CRGRC_OK\fP is set to \f(CRLL_WARNING\fP. The
level is further refined for specific GeoCOM codes:
.sp
.if n .RS 4
.nf
.fam C
\-\- dmgrc.conf
dmgrc = {
  logger = "dmlogger",
  node = "dummy\-node",
  response = "grc",
  level = LL_WARNING,
  levels = {
    debug = { GRC_ABORT, GRC_SHUT_DOWN, GRC_NO_EVENT },
    info = { GRC_SLEEP_NODE, GRC_NA, GRC_STOPPED },
    warning = { GRC_TMC_ACCURACY_GUARANTEE, GRC_AUT_NO_TARGET },
    error = { GRC_FATAL },
    critical = {}
  },
  debug = false,
  verbose = true
}
.fam
.fi
.if n .RE
.sp
Pass the path of the configuration file through the command\-line argument:
.sp
.if n .RS 4
.nf
.fam C
$ dmgrc \-n dmgrc \-c /usr/local/etc/dmpack/dmgrc.conf
.fam
.fi
.if n .RE
.sp
The name argument must match the name of the configuration table.
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2025 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel