'\" t
.\"     Title: dmlog
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-05-01
.\"    Manual: User Commands
.\"    Source: DMLOG
.\"  Language: English
.\"
.TH "DMLOG" "1" "2025-05-01" "DMLOG" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmlog \- sends log to POSIX message queue
.SH "SYNOPSIS"
.sp
\fBdmlog\fP \-\-help
.sp
\fBdmlog\fP \-\-version
.sp
\fBdmlog\fP \-\-\fBnode\fP \fIid\fP \-\-\fBmessage\fP \fIstring\fP [\-\-\fBlogger\fP \fIname\fP] [\-\-\fBlevel\fP \fIn\fP]
[\-\-\fBerror\fP \fIn\fP] [\-\-\fBnode\fP \fIid\fP] [\-\-\fBsensor\fP \fIid\fP] [\-\-\fBtarget\fP \fIid\fP]
[\-\-\fBobserv\fP \fIid\fP] [\-\-\fBsource\fP \fIsource\fP] [\-\-\fBverbose\fP]
.SH "DESCRIPTION"
.sp
The \fBdmlog\fP utility forwards a log message to the POSIX message queue of a
\fIdmlogger(1)\fP instance. Argument \f(CR\-\-message\fP is mandatory. Pass the name of
the \fIdmlogger\fP or \fIdmrecv\fP instance to send the log to through command\-line
argument \f(CR\-\-logger\fP. Alternatively, set environment variable \f(CRDMLOGGER\fP to the
name of the logger. The command\-line argument overwrites the environment
variable. The default log level is \f(CRinfo\fP (2). Valid log levels are \f(CRdebug\fP
(1), \f(CRinfo\fP (2), \f(CRwarning\fP (3), \f(CRerror\fP (4), \f(CRcritical\fP (5), and \f(CRuser\fP (6).
The program terminates after log transmission.
.SH "OPTIONS"
.sp
\fB\-\-error\fP, \fB\-e\fP \fIn\fP
.RS 4
DMPACK error code (>= 0).
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Print available command\-line arguments and quit.
.RE
.sp
\fB\-\-level\fP, \fB\-L\fP \fIlevel\fP
.RS 4
Log level, from \f(CRdebug\fP (1) to \f(CRuser\fP (6) The default level is \f(CRinfo\fP (2).
The argument may be an integer or log level name string.
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of logger instance and POSIX message queue. If the command\-line argument
is not passed and the environment variable \f(CRDMLOGGER\fP is not set, the log
messages will not be transmitted via POSIX message queue.
.RE
.sp
\fB\-\-message\fP, \fB\-m\fP \fIstring\fP
.RS 4
Log message (max. 512 characters).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Node id.
.RE
.sp
\fB\-\-observ\fP, \fB\-O\fP \fIid\fP
.RS 4
Observation id (UUIDv4).
.RE
.sp
\fB\-\-sensor\fP, \fB\-S\fP \fIid\fP
.RS 4
Sensor id.
.RE
.sp
\fB\-\-source\fP, \fB\-Z\fP \fIsource\fP
.RS 4
Name of log message source (sender).
.RE
.sp
\fB\-\-target\fP, \fB\-T\fP \fIid\fP
.RS 4
Target id.
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Print version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Log has been sent.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Program execution failed.
.RE
.SH "EXAMPLE"
.sp
Send a log message to the POSIX message queue of logger \f(CRdmlogger\fP:
.sp
.if n .RS 4
.nf
.fam C
$ dmlog \-\-node dummy\-node \-\-level warning \-\-message "low battery" \-\-source test \-\-verbose
2022\-12\-09T22:50:44.161000+01:00 [WARNING ] test \- low battery
.fam
.fi
.if n .RE
.sp
The logger will receive the log message and insert it into the log database (if
the log level is greater or equal the minimum log level):
.sp
.if n .RS 4
.nf
.fam C
$ dmlogger \-\-node dummy\-node \-\-database log.sqlite \-\-verbose
2022\-12\-09T22:50:44.161000+01:00 [WARNING] test \- low battery
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fIdmlogger(1)\fP
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2025 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel