.TH "DMREPORT" "1" "" "Version 2.0.0" "User Commands"
.SH NAME
dmreport \(en creates reports containing plots and logs
.SH SYNOPSIS
\f[B]dmreport\f[R] \-\-help
.PP
\f[B]dmreport\f[R] \-\-version
.PP
\f[B]dmreport\f[R] \-\-\f[B]config\f[R] \f[I]file\f[R]
[\-\-\f[B]name\f[R] \f[I]name\f[R]] [\-\-\f[B]node\f[R] \f[I]id\f[R]]
[\-\-\f[B]from\f[R] \f[I]timestamp\f[R]] [\-\-\f[B]to\f[R]
\f[I]timestamp\f[R]] [\-\-\f[B]format\f[R] \f[I]name\f[R]]
[\-\-\f[B]output\f[R] \f[I]file\f[R]] [\-\-\f[B]style\f[R]
\f[I]file\f[R]]
.PP
\f[B]dmreport\f[R] \-\-\f[B]config\f[R] \f[I]file\f[R]
[\-\-\f[B]name\f[R] \f[I]name\f[R]]
.SH DESCRIPTION
The \f[B]dmreport\f[R] program generates reports in HTML, PDF, or
PostScript format, containing plots of observations and/or log messages
selected from database.
Plots are created by calling \f[I]gnuplot(1)\f[R] and inlining the
returned image.
Reports in HTML format may contain GIF, PNG, or SVG images as
base64\-encoded data URI.
Reports in PostScript and PDF format are generated with
\f[I]groff(1)\f[R] and support only EPS images.
Any style sheet file with classless CSS can be included to alter the
presentation of the HTML report.
The output of \f[B]dmreport\f[R] is a single HTML, PDF, or PostScript
file.
.PP
A configuration file is mandatory to create reports.
Only a few parameters may be set through command\-line arguments.
Passed command\-line arguments have priority over settings in the
configuration file.
.SH OPTIONS
.TP
\f[B]\-\-config\f[R], \f[B]\-c\f[R] \f[I]file\f[R]
File path to configuration file.
.TP
\f[B]\-\-format\f[R], \f[B]\-F\f[R] [html|ps|pdf]
Output file format, either HTML5, PostScript, or PDF.
.TP
\f[B]\-\-from\f[R], \f[B]\-B\f[R] \f[I]timestamp\f[R]
Start of the time range in ISO 8601.
.TP
\f[B]\-\-help\f[R], \f[B]\-h\f[R]
Print available command\-line arguments and quit.
.TP
\f[B]\-\-name\f[R], \f[B]\-n\f[R] \f[I]name\f[R]
Name of instance and table in given configuration file (default is
\f[CR]dmreport\f[R]).
.TP
\f[B]\-\-node\f[R], \f[B]\-N\f[R] \f[I]id\f[R]
Select observations and log messages of the given node id.
.TP
\f[B]\-\-output\f[R], \f[B]\-o\f[R] \f[I]file\f[R]
File path of the generated report.
Additional format descriptors are replaced with their values to set date
and time dynamically (\f[CR]%Y\f[R], \f[CR]%M\f[R], \f[CR]%D\f[R],
\f[CR]%h\f[R], \f[CR]%m\f[R], \f[CR]%s\f[R]).
.TP
\f[B]\-\-style\f[R], \f[B]\-C\f[R] \f[I]file\f[R]
File path to the classless CSS file to be included in the report
(optional).
.TP
\f[B]\-\-to\f[R], \f[B]\-E\f[R] \f[I]timestamp\f[R]
End of the time range in ISO 8601.
.TP
\f[B]\-\-version\f[R], \f[B]\-v\f[R]
Print version information and quit.
.SH EXIT STATUS
.TP
\f[B]0\f[R]
Success.
Report was created.
.TP
\f[B]1\f[R]
Failure.
Report creation failed.
.SH EXAMPLE
Write a report to file \f[CR]report.html\f[R] based on settings in
\f[CR]dmreport.conf\f[R]:
.IP
.EX
$ dmreport \-n dmreport \-c dmreport.conf \-B 2020\-01\-01 \(rs
  \-E 2021\-01\-01 \-f html \-o report.html
.EE
