'\" t
.\"     Title: dmsend
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.22
.\"      Date: 2024-04-06
.\"    Manual: User Commands
.\"    Source: DMSEND
.\"  Language: English
.\"
.TH "DMSEND" "1" "2024-04-06" "DMSEND" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmsend \- sends observations and logs to POSIX message queues
.SH "SYNOPSIS"
.sp
\fBdmsend\fP \-\-help
.sp
\fBdmsend\fP \-\-version
.sp
\fBdmsend\fP \-\-\fBtype\fP [log|observ] \-\-\fBformat\fP [csv|nml] \-\-\fBinput\fP \fIfile\fP
[\-\-\fBreceiver\fP \fIname\fP] [\-\-\fBname\fP \fIname\fP] [\-\-\fBnode\fP \fIid\fP] [\-\-\fBlogger\fP \fIname\fP]
[\-\-\fBdebug\fP] [\-\-\fBforward\fP] [\-\-\fBverbose\fP]
.sp
\fBdmsend\fP \-\-\fBconfig\fP \fIfile\fP [\-\-\fBname\fP \fIname\fP]
.SH "DESCRIPTION"
.sp
The \fBdmsend\fP program reads observations or logs in CSV or Fortran 95 Namelist
format, and sends them sequentially to the POSIX message queue of the given
receiver. The data is either read from file or from standard input. If the input
data is of type \f(CRobserv\fP and the argument \f(CR\-\-forward\fP is passed, each
observation will be sent to its next specified receiver in the receivers list.
If no receivers are declared, or if the end of the receivers list is reached,
the observation will not be forwarded.
.sp
The program settings are passed through command\-line arguments or an optional
configuration file. The arguments overwrite settings from file.
.SH "OPTIONS"
.sp
\fB\-\-config\fP, \fB\-c\fP \fIfile\fP
.RS 4
Path to configuration file.
.RE
.sp
\fB\-\-debug\fP, \fB\-D\fP
.RS 4
Forward logs messages of level \f(CRLVL_DEBUG\fP via IPC (if logger is set).
.RE
.sp
\fB\-\-format\fP, \fB\-f\fP [csv|nml]
.RS 4
Input format, either CSV or Fortran 95 Namelist.
.RE
.sp
\fB\-\-forward\fP, \fB\-F\fP
.RS 4
Forward observations to the next specified receiver in the receivers list. Not
allowed in combination with argument \f(CR\-\-receiver\fP.
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of logger. If set, sends logs to \fIdmlogger(1)\fP process of given name.
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Output available command\-line arguments and quit.
.RE
.sp
\fB\-\-input\fP, \fB\-i\fP
.RS 4
Path to input file, either in CSV or Namelist format. Reads records from
\fIstdin\fP if not passed or set to \f(CR\-\fP.
.RE
.sp
\fB\-\-name\fP, \fB\-n\fP \fIname\fP
.RS 4
Name of program instance and configuration (default is \f(CRdmsend\fP).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Optional node id.
.RE
.sp
\fB\-\-receiver\fP, \fB\-r\fP \fIname\fP
.RS 4
Name of the observation or log receiver, without leading \f(CR/\fP. Not allowed in
combination with argument \f(CR\-\-forward\fP.
.RE
.sp
\fB\-\-type\fP, \fB\-t\fP [log|observ]
.RS 4
Data type to send, either log or observation.
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log messages to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Output version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Program terminated normally.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Program execution failed.
.RE
.SH "EXAMPLE"
.sp
Read observation from Namelist file \f(CRobserv.nml\fP and send it to the next
specified receiver:
.sp
.if n .RS 4
.nf
.fam C
$ dmsend \-\-type observ \-\-format nml \-\-input observ.nml \-\-forward
.fam
.fi
.if n .RE
.sp
Send logs in CSV file \f(CRlogs.csv\fP sequentially to process \f(CRdmrecv\fP:
.sp
.if n .RS 4
.nf
.fam C
$ dmsend \-\-receiver dmrecv \-\-type log \-\-format csv \-\-input logs.csv
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fIdmrecv(1)\fP
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2024 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel