'\" t
.\"     Title: dmserial
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2024-02-21
.\"    Manual: User Commands
.\"    Source: DMSERIAL
.\"  Language: English
.\"
.TH "DMSERIAL" "1" "2024-02-21" "DMSERIAL" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmserial \- reads observations from TTY/PTY
.SH "SYNOPSIS"
.sp
\fBdmserial\fP \-\-help
.sp
\fBdmserial\fP \-\-version
.sp
\fBdmserial\fP \-\-\fBconfig\fP \fIfile\fP [\-\-\fBname\fP \fIname\fP] [\-\-\fBnode\fP \fIid\fP] [\-\-\fBsensor\fP \fIid\fP]
[\-\-\fBlogger\fP \fIname\fP] [\-\-\fBtty\fP \fIpath\fP] [\-\-\fBbaudrate\fP \fIn\fP] [\-\-\fBbytesize\fP \fIn\fP]
[\-\-\fBstopbits\fP \fIn\fP] [\-\-\fBparity\fP \fIname\fP] [\-\-\fBtimeout\fP \fIn\fP] [\-\-\fBformat\fP \fIname\fP]
[\-\-\fBoutput\fP \fIfile\fP] [\-\-\fBdtr\fP] [\-\-\fBrts\fP] [\-\-\fBdebug\fP] [\-\-\fBverbose\fP]
.SH "DESCRIPTION"
.sp
The \fBdmserial\fP program sends requests to a sensor connected via
USB/RS\-232/RS\-422/RS\-485. Sensor commands and responses are sent/received
through a teletype (TTY) device provided by the operating system. A
pseudo\-terminal (PTY) may be used to connect a virtual sensor.
.sp
Each request of an observation must contains the raw request intended for the
sensor in attribute \f(CRrequest\fP. Response values are extracted by group from the
raw response using the given regular expression pattern. Each group name must
match a response name. Response names are limited to eight characters.
.sp
Observations will be forwarded to the next receiver via POSIX message queue if
any receiver is specified. The program can act as a sole data logger if output
and format are set. If the output path is set to \f(CR\-\fP, observations are printed
to \fIstdout\fP, else to file.
.sp
A configuration file is required to configure the jobs to perform. Each
observation must have a valid target id. The database must contain the specified
node, sensor, and targets.
.SH "OPTIONS"
.sp
\fB\-\-baudrate\fP, \fB\-B\fP \fIn\fP
.RS 4
Number of symbols transmitted per second. The following baud rates are
supported: 50, 75, 110, 134, 150, 200, 300, 600, 1200, 1800, 2400, 4800, 9600,
19200, 38400, 57600, 115200, 230400, 460800, 921600.
.RE
.sp
\fB\-\-bytesize\fP, \fB\-Z\fP \fIn\fP
.RS 4
Byte size (5, 6, 7, 8).
.RE
.sp
\fB\-\-config\fP, \fB\-c\fP \fIfile\fP
.RS 4
File path to the configuration file.
.RE
.sp
\fB\-\-debug\fP, \fB\-D\fP
.RS 4
Forward logs messages of level DEBUG via IPC (if logger is set).
.RE
.sp
\fB\-\-dtr\fP, \fB\-Q\fP
.RS 4
Enable Data Terminal Ready (DTR).
.RE
.sp
\fB\-\-format\fP, \fB\-f\fP [csv|jsonl]
.RS 4
Output format of observations if \f(CR\-\-output\fP is set. Either CSV or JSON Lines.
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Output available command\-line arguments and quit.
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of logger. If set, sends logs to \fIdmlogger(1)\fP process of given name.
.RE
.sp
\fB\-\-name\fP, \fB\-n\fP \fIname\fP
.RS 4
Name of program instance and configuration (default is \f(CRdmserial\fP).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Node id.
.RE
.sp
\fB\-\-output\fP, \fB\-o\fP \fIfile\fP
.RS 4
Output file to append observations to (\f(CR\-\fP for \fIstdout\fP).
.RE
.sp
\fB\-\-parity\fP, \fB\-P\fP [none|even|odd]
.RS 4
Parity bits (\f(CRnone\fP, \f(CReven\fP, or \f(CRodd\fP).
.RE
.sp
\fB\-\-rts\fP, \fB\-R\fP
.RS 4
Enable Request To Send (RTS).
.RE
.sp
\fB\-\-sensor\fP, \fB\-S\fP \fIid\fP
.RS 4
Sensor id.
.RE
.sp
\fB\-\-stopbits\fP, \fB\-O\fP \fIn\fP
.RS 4
Number of stop bits (1, 2).
.RE
.sp
\fB\-\-timeout\fP, \fB\-T\fP \fIn\fP
.RS 4
Connection timeout in seconds.
.RE
.sp
\fB\-\-tty\fP, \fB\-Y\fP \fIpath\fP
.RS 4
Path to TTY/PTY device (for example, \f(CR/dev/ttyU0\fP).
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log messages to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Output version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Process terminated without errors.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Process failed.
.RE
.SH "EXAMPLE"
.sp
Read the jobs to perform from configuration file and execute them sequentially:
.sp
.if n .RS 4
.nf
.fam C
$ dmserial \-\-name dmserial \-\-config /usr/local/etc/dmpack/dmserial.conf \-\-verbose
.fam
.fi
.if n .RE
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2024 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel