'\" t
.\"     Title: dmsystem
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-08-20
.\"    Manual: User Commands
.\"    Source: DMSYSTEM
.\"  Language: English
.\"
.TH "DMSYSTEM" "1" "2025-08-20" "DMSYSTEM" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmsystem \- monitors system parameters
.SH "SYNOPSIS"
.sp
\fBdmsystem\fP \-\-help
.sp
\fBdmsystem\fP \-\-version
.sp
\fBdmsystem\fP \-\-\fBnode\fP \fIid\fP \-\-\fBsensor\fP \fIid\fP \-\-\fBtarget\fP \fIid\fP [\-\-\fBreceiver\fP \fIname\fP]
[\-\-\fBinterval\fP \fIseconds\fP] [\-\-\fBcount\fP \fIn\fP] [\-\-\fBname\fP \fIname\fP] [\-\-\fBlogger\fP \fIname\fP]
[\-\-\fBdebug\fP] [\-\-\fBverbose\fP]
.sp
\fBdmsystem\fP \-\-\fBconfig\fP \fIfile\fP [\-\-\fBname\fP \fIname\fP]
.SH "DESCRIPTION"
.sp
A system monitor to watch free disk space and disk capacity, database sizes,
load average, CPU temperature, and system uptime. The file system for the free
disk space and disk capacity responses is determined through a given file or
directory path. The paths to the log and observation databases have to be given
in the configuration file.
.sp
cpu_temp
.RS 4
CPU temperature [°C]. Disabled by default.
.RE
.sp
disk_free
.RS 4
Free disk space [Byte]. Requires file or directory path.
.RE
.sp
disk_capacity
.RS 4
Disk capacity [%]. Requires file or directory path.
.RE
.sp
load_avg1
.RS 4
Load average, last minute. Enabled by default.
.RE
.sp
load_avg5
.RS 4
Load average, last 5 minutes. Enabled by default.
.RE
.sp
load_avg15
.RS 4
Load average, last 15 minutes. Enabled by default.
.RE
.sp
uptime
.RS 4
System uptime [sec]. Enabled by default.
.RE
.SH "OPTIONS"
.sp
\fB\-\-config\fP, \fB\-c\fP \fIfile\fP
.RS 4
File path to the configuration file.
.RE
.sp
\fB\-\-count\fP, \fB\-C\fP \fIn\fP
.RS 4
Number of observations to create. No limit if count is set to 0 (default).
.RE
.sp
\fB\-\-debug\fP, \fB\-D\fP
.RS 4
Forward logs messages of level \f(CRLL_DEBUG\fP via IPC (if logger is set).
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Print available command\-line arguments and quit.
.RE
.sp
\fB\-\-interval\fP, \fB\-I\fP \fIseconds\fP
.RS 4
Interval in seconds in which to read the system parameters.
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of logger. If set, sends logs to \fIdmlogger(1)\fP process of given name.
.RE
.sp
\fB\-\-name\fP, \fB\-n\fP \fIname\fP
.RS 4
Name of program instance and configuration (default is \f(CRdmsystem\fP).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Node id.
.RE
.sp
\fB\-\-receiver\fP, \fB\-r\fP \fIname\fP
.RS 4
Name of the observation receiver, without leading \f(CR/\fP.
.RE
.sp
\fB\-\-sensor\fP, \fB\-S\fP \fIid\fP
.RS 4
Sensor id.
.RE
.sp
\fB\-\-target\fP, \fB\-T\fP \fIid\fP
.RS 4
Target id.
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log messages to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Print version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Process terminated without errors.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Process failed.
.RE
.SH "EXAMPLE"
.sp
Read system parameters in an interval of 60 seconds and forward observations to
\f(CRdmrecv\fP:
.sp
.if n .RS 4
.nf
.fam C
$ dmsystem \-N dummy\-node \-S dummy\-sensor \-T dummy\-target \(rs
  \-I 60 \-r dmrecv \-V
.fam
.fi
.if n .RE
.sp
Start \f(CRdmrecv\fP with:
.sp
.if n .RS 4
.nf
.fam C
$ dmrecv \-n dmrecv \-t observ \-f jsonl \-o "\-" \-V
.fam
.fi
.if n .RE
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2025 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel