'\" t
.\"     Title: dmuuid
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-08-15
.\"    Manual: User Commands
.\"    Source: DMUUID
.\"  Language: English
.\"
.TH "DMUUID" "1" "2025-08-15" "DMUUID" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmuuid \- generates pseudo\-random UUIDs
.SH "SYNOPSIS"
.sp
\fBdmuuid\fP \-\-help
.sp
\fBdmuuid\fP \-\-version
.sp
\fBdmuuid\fP [\-\-\fBcount\fP \fIn\fP] [\-\-\fBhyphens\fP]
.sp
\fBdmuuid\fP \-\-\fBconvert\fP < \fIfile\fP
.SH "DESCRIPTION"
.sp
The \fBdmuuid\fP program generates pseudo\-random UUIDs. By default, DMPACK uses 32
characters long UUIDv4 identifers in hexadecimal format (without hyphens). If
command\-line flag \f(CR\-\-hyphens\fP is set, 36 characters long identifiers with
hyphens are returned. The option \f(CR\-\-convert\fP expects UUIDs to be passed via
standard input. Invalid identifiers will be replaced with the default UUIDv4.
.SH "OPTIONS"
.sp
\fB\-\-convert\fP, \fB\-c\fP
.RS 4
Add hyphens to hexadecimal UUIDs passed via \fIstdin\fP.
.RE
.sp
\fB\-\-count\fP, \fB\-n\fP \fIn\fP
.RS 4
Number of UUIDs to generate (default: 1).
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Print available command\-line arguments and quit.
.RE
.sp
\fB\-\-hyphens\fP, \fB\-p\fP
.RS 4
Return 36 characters long UUIDs with hyphens.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Print version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
UUID generation was successful.
.RE
.sp
\fB1\fP
.RS 4
Failure.
UUID generation failed.
.RE
.SH "EXAMPLE"
.sp
Create three random identifiers:
.sp
.if n .RS 4
.nf
.fam C
$ dmuuid \-n 3
6827049760c545ad80d4082cc50203e8
ad488d0b8edd4c6c94582e702a810ada
3d3eee7ae1fb4259b5df72f854aaa369
.fam
.fi
.if n .RE
.sp
Add hyphens to a hexadecimal UUIDv4:
.sp
.if n .RS 4
.nf
.fam C
$ echo "3d3eee7ae1fb4259b5df72f854aaa369" | dmuuid \-c
3d3eee7a\-e1fb\-4259\-b5df\-72f854aaa369
.fam
.fi
.if n .RE
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://www.dabamos.de/" "" ""
.SH "COPYING"
.sp
Copyright \(co 2025 Philipp Engel.
.br
Free use of this software is granted under the terms of the ISC Licence.
.SH "AUTHOR"
.sp
Philipp Engel