'\" t
.\"     Title: dmved
.\"    Author: Philipp Engel
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-09-02
.\"    Manual: User Commands
.\"    Source: DMVED
.\"  Language: English
.\"
.TH "DMVED" "1" "2025-09-02" "DMVED" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dmved \- reads status of connected MPPT charger or battery shunt
.SH "SYNOPSIS"
.sp
\fBdmved\fP \-\-help
.sp
\fBdmved\fP \-\-version
.sp
\fBdmved\fP \-\-\fBconfig\fP \fIfile\fP [\-\-\fBname\fP \fIname\fP] [\-\-\fBnode\fP \fIid\fP] [\-\-\fBsensor\fP \fIid\fP]
[\-\-\fBtarget\fP \fIid\fP] [\-\-\fBdevice\fP \fItype\fP] [\-\-\fBpath\fP \fIpath\fP] [\-\-\fBreceiver\fP \fIname\fP]
[\-\-\fBinterval\fP \fIseconds\fP] [\-\-\fBdump\fP \fIpath\fP] [\-\-\fBlogger\fP \fIname\fP] [\-\-\fBdebug\fP]
[\-\-\fBverbose\fP]
.SH "DESCRIPTION"
.sp
This program captures status data received from a connected Maximum Power Point
Tracking (MPPT) solar charge controller or SmartShunt battery monitor by
Victron Energy, using the VE.Direct protocol. Only the BlueSolar/SmartSolar
MPPT series and the SmartShunt monitor are supported. The serial port will be
configured to 19200 baud (8N1). Observations are forwarded via message queue in
the given interval if a receiver is specified.
.sp
The following VE.Direct fields are captured, depending on the device:
.sp
Alarm
.RS 4
Alarm condition active (on/off).
.RE
.sp
AR
.RS 4
Alarm reason.
.RE
.sp
CE
.RS 4
Consumed amp hours (mAh).
.RE
.sp
CS
.RS 4
State of operation.
.RE
.sp
DM
.RS 4
Mid\-point deviation of the battery bank (%/10).
.RE
.sp
ERR
.RS 4
Error code.
.RE
.sp
H1
.RS 4
Depth of the deepest discharge (mAh).
.RE
.sp
H2
.RS 4
Depth of the last discharge (mAh).
.RE
.sp
H3
.RS 4
Depth of the average discharge (mAh).
.RE
.sp
H4
.RS 4
Number of charge cycles.
.RE
.sp
H5
.RS 4
Number of full discharges.
.RE
.sp
H6
.RS 4
Cumulative amp hours drawn (mAh).
.RE
.sp
H7
.RS 4
Minimum main (battery) voltage (mV).
.RE
.sp
H8
.RS 4
Maximum main (battery) voltage (mV).
.RE
.sp
H9
.RS 4
Number of seconds since last full charge (sec).
.RE
.sp
H10
.RS 4
Number of automatic synchronisations.
.RE
.sp
H11
.RS 4
Number of low main voltage alarms.
.RE
.sp
H12
.RS 4
Number of high main voltage alarms.
.RE
.sp
H15
.RS 4
Minimum auxiliary (battery) voltage (mV).
.RE
.sp
H16
.RS 4
Maximum auxiliary (battery) voltage (mV).
.RE
.sp
H17
.RS 4
Amount of produced energy (kWh/100).
.RE
.sp
H18
.RS 4
Amount of consumed energy (kWh/100).
.RE
.sp
H19
.RS 4
Yield total (kWh/100).
.RE
.sp
H20
.RS 4
Yield today (kWh/100).
.RE
.sp
H21
.RS 4
Maximum power today (W).
.RE
.sp
H22
.RS 4
Yield yesterday (kWh/100).
.RE
.sp
H23
.RS 4
Maximum power yesterday (W).
.RE
.sp
HSDS
.RS 4
Day sequence number (0 to 364).
.RE
.sp
I
.RS 4
Main or channel 1 battery current (mA).
.RE
.sp
IL
.RS 4
Load current (mA).
.RE
.sp
LOAD
.RS 4
Load output state (on/off).
.RE
.sp
MON
.RS 4
DC monitor mode.
.RE
.sp
MPPT
.RS 4
Tracker operation mode.
.RE
.sp
OR
.RS 4
Off reason.
.RE
.sp
P
.RS 4
Instantaneous power (W).
.RE
.sp
PPV
.RS 4
Panel power (W).
.RE
.sp
Relay
.RS 4
Relay state (on/off).
.RE
.sp
SOC
.RS 4
State\-of\-charge (%/10).
.RE
.sp
T
.RS 4
Battery temperature (degrees Celsius).
.RE
.sp
TTG
.RS 4
Time\-to\-go (min).
.RE
.sp
V
.RS 4
Main or channel 1 (battery) voltage (mV).
.RE
.sp
VM
.RS 4
Mid\-point voltage of the battery bank (mV).
.RE
.sp
VPV
.RS 4
Panel voltage (mV).
.RE
.sp
VS
.RS 4
Auxiliary (starter) voltage (mV).
.RE
.sp
The response names equal the field names in lower\-case.
.SH "OPTIONS"
.sp
\fB\-\-config\fP, \fB\-c\fP \fIfile\fP
.RS 4
File path to the configuration file.
.RE
.sp
\fB\-\-debug\fP, \fB\-D\fP
.RS 4
Forward logs messages of level \f(CRLL_DEBUG\fP via IPC (if logger is set).
.RE
.sp
\fB\-\-device\fP, \fB\-d\fP [mppt|shunt]
.RS 4
Connected device, either MPPT or SmartShunt.
.RE
.sp
\fB\-\-dump\fP, \fB\-o\fP \fIpath\fP
.RS 4
Path of file or named pipe to dump received raw data to.
.RE
.sp
\fB\-\-help\fP, \fB\-h\fP
.RS 4
Print available command\-line arguments and quit.
.RE
.sp
\fB\-\-interval\fP, \fB\-I\fP \fIseconds\fP
.RS 4
Observation emit interval in seconds (default is 60 seconds).
.RE
.sp
\fB\-\-logger\fP, \fB\-l\fP \fIname\fP
.RS 4
Name of logger. If set, sends logs to \fIdmlogger(1)\fP process of given name.
.RE
.sp
\fB\-\-name\fP, \fB\-n\fP \fIname\fP
.RS 4
Name of program instance and configuration (default is \f(CRdmved\fP).
.RE
.sp
\fB\-\-node\fP, \fB\-N\fP \fIid\fP
.RS 4
Node id.
.RE
.sp
\fB\-\-path\fP, \fB\-p\fP \fIpath\fP
.RS 4
Path to TTY device (for example, \f(CR/dev/ttyUSB0\fP).
.RE
.sp
\fB\-\-receiver\fP, \fB\-r\fP \fIname\fP
.RS 4
Name of the observation receiver, without leading \f(CR/\fP.
.RE
.sp
\fB\-\-sensor\fP, \fB\-S\fP \fIid\fP
.RS 4
Sensor id.
.RE
.sp
\fB\-\-target\fP, \fB\-T\fP \fIid\fP
.RS 4
Target id.
.RE
.sp
\fB\-\-verbose\fP, \fB\-V\fP
.RS 4
Print log messages to \fIstderr\fP.
.RE
.sp
\fB\-\-version\fP, \fB\-v\fP
.RS 4
Print version information and quit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
Process terminated without errors.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Process failed.
.RE
.SH "ENVIRONMENT"
.sp
\fBDM_LOGGER\fP
.RS 4
Name of logger instance to send logs to.
.RE
.sp
\fBNO_COLOR\fP
.RS 4
Disable ANSI colour output.
.RE
.SH "EXAMPLE"
.sp
Read status data from MPPT connected via TTL:
.sp
.if n .RS 4
.nf
.fam C
$ dmved \-n dmved \-c /usr/local/etc/dmpack/dmved.conf \-V
.fam
.fi
.if n .RE
.SH "AUTHOR"
.sp
Philipp Engel