name        = "dmpack"
version     = "0.9.7"
license     = "ISC"
author      = "Philipp Engel"
maintainer  = "@interkosmos"
copyright   = "Copyright (c) 2025, Philipp Engel"
description = "Deformation Monitoring Package (DMPACK) for automated control measurements in engineering geodesy"
keywords    = [ "geodesy", "monitoring", "engineering", "sensors", "iot" ]

[library]
source-dir = "src"

[install]
library = true

[dependencies]
fortran-curl    = { git = "https://github.com/interkosmos/fortran-curl.git" }
fortran-modbus  = { git = "https://github.com/interkosmos/fortran-modbus.git" }
fortran-lua54   = { git = "https://github.com/interkosmos/fortran-lua54.git" }
fortran-pcre2   = { git = "https://github.com/interkosmos/fortran-pcre2.git" }
fortran-sqlite3 = { git = "https://github.com/interkosmos/fortran-sqlite3.git" }
fortran-unix    = { git = "https://github.com/interkosmos/fortran-unix.git" }
fortran-xmpp    = { git = "https://github.com/interkosmos/fortran-xmpp.git" }
fortran-zlib    = { git = "https://github.com/interkosmos/fortran-zlib.git" }
fortran-zstd    = { git = "https://github.com/interkosmos/fortran-zstd.git" }

[build]
auto-examples    = false
auto-executables = false
auto-tests       = false
external-modules = [ "hdf5", "h5lib", "h5tb" ]

[[executable]]
name = "dmapi"
main = "dmapi.f90"
link = [ "fcgi", "sqlite3", "z", "zstd" ]

[[executable]]
name = "dmbackup"
main = "dmbackup.f90"
link = [ "sqlite3" ]

[[executable]]
name = "dmbeat"
main = "dmbeat.f90"
link = [ "curl", "lua-5.4", "rt", "z", "zstd" ]

[[executable]]
name = "dmbot"
main = "dmbot.f90"
link = [ "expat", "strophe", "lua-5.4", "ssl", "rt", "sqlite3", "z" ]

[[executable]]
name = "dmdb"
main = "dmdb.f90"
link = [ "lua-5.4", "pthread", "rt", "sqlite3" ]

[[executable]]
name = "dmdbctl"
main = "dmdbctl.f90"
link = [ "sqlite3" ]

[[executable]]
name = "dmdwd"
main = "dmdwd.f90"
link = [ "curl", "lua-5.4", "rt", "z" ]

[[executable]]
name = "dmexport"
main = "dmexport.f90"
link = [ "sqlite3" ]

[[executable]]
name = "dmfeed"
main = "dmfeed.f90"
link = [ "lua-5.4", "sqlite3" ]

[[executable]]
name = "dmfs"
main = "dmfs.f90"
link = [ "lua-5.4", "pcre2-8", "rt" ]

[[executable]]
name = "dmgrc"
main = "dmgrc.f90"
link = [ "lua-5.4", "pcre2-8", "rt" ]

[[executable]]
name = "dmimport"
main = "dmimport.f90"
link = [ "sqlite3" ]

[[executable]]
name = "dminfo"
main = "dminfo.f90"
link = [ "sqlite3" ]

[[executable]]
name = "dminit"
main = "dminit.f90"
link = [ "sqlite3" ]

[[executable]]
name = "dmlog"
main = "dmlog.f90"
link = [ "rt" ]

[[executable]]
name = "dmlogger"
main = "dmlogger.f90"
link = [ "lua-5.4", "pthread", "rt", "sqlite3" ]

[[executable]]
name = "dmlua"
main = "dmlua.f90"
link = [ "lua-5.4", "rt" ]

[[executable]]
name = "dmmb"
main = "dmmb.f90"
link = [ "lua-5.4", "modbus", "rt" ]

[[executable]]
name = "dmmbctl"
main = "dmmbctl.f90"
link = [ "modbus" ]

[[executable]]
name = "dmpipe"
main = "dmpipe.f90"
link = [ "lua-5.4", "pcre2-8", "rt" ]

[[executable]]
name = "dmplot"
main = "dmplot.f90"
link = [ "lua-5.4", "sqlite3" ]

[[executable]]
name = "dmrecv"
main = "dmrecv.f90"
link = [ "lua-5.4", "rt" ]

[[executable]]
name = "dmreport"
main = "dmreport.f90"
link = [ "lua-5.4", "sqlite3" ]

[[executable]]
name = "dmsend"
main = "dmsend.f90"
link = [ "lua-5.4", "rt" ]

[[executable]]
name = "dmserial"
main = "dmserial.f90"
link = [ "lua-5.4", "pcre2-8", "rt" ]

[[executable]]
name = "dmsync"
main = "dmsync.f90"
link = [ "curl", "lua-5.4", "pthread", "rt", "sqlite3", "z", "zstd" ]

[[executable]]
name = "dmsystem"
main = "dmsystem.f90"
link = [ "lua-5.4", "rt" ]

[[executable]]
name = "dmuuid"
main = "dmuuid.f90"

[[executable]]
name = "dmved"
main = "dmved.f90"
link = [ "lua-5.4", "rt" ]

[[executable]]
name = "dmweb"
main = "dmweb.f90"
link = [ "sqlite3" ]

[[test]]
name = "dmtestapi"
main = "dmtestapi.f90"

[[test]]
name = "dmtestascii"
main = "dmtestascii.f90"

[[test]]
name = "dmtestatom"
main = "dmtestatom.f90"

[[test]]
name = "dmtestbase64"
main = "dmtestbase64.f90"

[[test]]
name = "dmtestc"
main = "dmtestc.f90"

[[test]]
name = "dmtestcgi"
main = "dmtestcgi.f90"

[[test]]
name = "dmtestconfig"
main = "dmtestconfig.f90"

[[test]]
name = "dmtestcrypto"
main = "dmtestcrypto.f90"
link = [ "crypto" ]

[[test]]
name = "dmtestcsv"
main = "dmtestcsv.f90"

[[test]]
name = "dmtestdb"
main = "dmtestdb.f90"
link = [ "sqlite3" ]

[[test]]
name = "dmtestdp"
main = "dmtestdp.f90"

[[test]]
name = "dmtestdwd"
main = "dmtestdwd.f90"
link = [ "curl", "rt", "z" ]

[[test]]
name = "dmtestfile"
main = "dmtestfile.f90"

[[test]]
name = "dmtestfreebsd"
main = "dmtestfreebsd.f90"

[[test]]
name = "dmtestftp"
main = "dmtestftp.f90"
link = [ "curl" ]

[[test]]
name = "dmtestgm"
main = "dmtestgm.f90"

[[test]]
name = "dmtesthash"
main = "dmtesthash.f90"

[[test]]
name = "dmtesthdf5"
main = "dmtesthdf5.f90"
link = [ "hdf5_fortran", "hdf5" ]

[[test]]
name = "dmtesthtml"
main = "dmtesthtml.f90"

[[test]]
name = "dmtestid"
main = "dmtestid.f90"

[[test]]
name = "dmtestjob"
main = "dmtestjob.f90"

[[test]]
name = "dmtestjson"
main = "dmtestjson.f90"

[[test]]
name = "dmtestlinux"
main = "dmtestlinux.f90"

[[test]]
name = "dmtestlog"
main = "dmtestlog.f90"

[[test]]
name = "dmtestlogger"
main = "dmtestlogger.f90"
link = [ "rt" ]

[[test]]
name = "dmtestlua"
main = "dmtestlua.f90"
link = [ "lua-5.4" ]

[[test]]
name = "dmtestmail"
main = "dmtestmail.f90"
link = [ "curl" ]

[[test]]
name = "dmtestmodbus"
main = "dmtestmodbus.f90"
link = [ "modbus" ]

[[test]]
name = "dmtestmqtt"
main = "dmtestmqtt.f90"
link = [ "curl" ]

[[test]]
name = "dmtestmqueue"
main = "dmtestmqueue.f90"
link = [ "rt" ]

[[test]]
name = "dmtestnet"
main = "dmtestnet.f90"

[[test]]
name = "dmtestnml"
main = "dmtestnml.f90"

[[test]]
name = "dmtestobserv"
main = "dmtestobserv.f90"

[[test]]
name = "dmtestpath"
main = "dmtestpath.f90"

[[test]]
name = "dmtestpipe"
main = "dmtestpipe.f90"

[[test]]
name = "dmtestplot"
main = "dmtestplot.f90"

[[test]]
name = "dmtestregex"
main = "dmtestregex.f90"
link = [ "pcre2-8" ]

[[test]]
name = "dmtestrpc"
main = "dmtestrpc.f90"
link = [ "curl", "z", "zstd" ]

[[test]]
name = "dmtestrts"
main = "dmtestrts.f90"

[[test]]
name = "dmteststring"
main = "dmteststring.f90"

[[test]]
name = "dmtestsystem"
main = "dmtestsystem.f90"

[[test]]
name = "dmtestthread"
main = "dmtestthread.f90"
link = [ "pthread" ]

[[test]]
name = "dmtesttime"
main = "dmtesttime.f90"

[[test]]
name = "dmtesttransform"
main = "dmtesttransform.f90"
link = [ "lapack", "blas" ]

[[test]]
name = "dmtesttty"
main = "dmtesttty.f90"

[[test]]
name = "dmtestunit"
main = "dmtestunit.f90"

[[test]]
name = "dmtestutil"
main = "dmtestutil.f90"

[[test]]
name = "dmtestuuid"
main = "dmtestuuid.f90"

[[test]]
name = "dmtestve"
main = "dmtestve.f90"

[[test]]
name = "dmtestversion"
main = "dmtestversion.f90"

[[test]]
name = "dmtestz"
main = "dmtestz.f90"
link = [ "z", "zstd" ]

[[test]]
name = "dmtestzlib"
main = "dmtestzlib.f90"
link = [ "z" ]

[[test]]
name = "dmtestzstd"
main = "dmtestzstd.f90"
link = [ "zstd" ]
