= dmbeat(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMBEAT

== NAME

dmbeat - sends status messages to an RPC server

== SYNOPSIS

*dmbeat* --help

*dmbeat* --version

*dmbeat* --*node* _id_ --*host* _host_ [--*port* _port_] [--*tls*]
[--*username* _user_] [--*password* _password_] [--*count* _n_]
[--*interval* _seconds_] [--*compression* _name_] [--*logger* _name_]
[--*debug*] [--*verbose*]

*dmbeat* --*config* _file_ [--*name* _name_]

== DESCRIPTION

This program is a heartbeat emitter that sends status messages to a remote
DMPACK HTTP-RPC API. The status messages include timestamp, system uptime, and
last connection error. The server may inspect this data to check if a client is
still running and has network access. The RPC endpoint is expected at
`[http|https]://<host>:<port>/api/v1/beat`. The heartbeat is transmitted in
Zstandard-compressed Fortran 95 Namelist format.

Passing the server credentials via the command-line arguments `--username` and
`--password` is insecure on multi-user operating systems and only recommended
for testing.

== OPTIONS

*--compression*, *-x* _name_::
  Compression library to use for payload data (`none`, `zlib`, `zstd`). The
  default is `zstd` (Z standard). Select `zlib` for deflate compression.

*--config*, *-c* _file_::
  Path to Lua-based configuration file.

*--count*, *-C* _n_::
  Maximum number of heartbeats to send. The default is 0 (unlimited).

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--help*, *-h*::
  Print available command-line arguments and quit.

*--host*, *-H* _host_::
  IP or FQDN of RPC host (for example, `127.0.0.1` or `example.com`).

*--interval*, *-I* _seconds_::
  Emit interval in seconds (default is 60 seconds).

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of instance and table in given configuration file (default is `dmbeat`).

*--node*, *-N* _id_::
  Sensor node id.

*--password*, *-P* _password_::
  RPC API password. Be aware that passing the credentials via command-line
  arguments is insecure and only recommended for testing.

*--port*, *-q* _port_::
  Port of RPC API server. The default port is 0 (automatic selection depending
  on protocol).

*--tls*, *-E*::
  Use TLS encryption.

*--username*, *-U* _user_::
  RPC API user name. If set, implies HTTP Basic Auth.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Print version information and quit.

== EXIT STATUS

*0*::
  Success.
  Beat has been transmitted.

*1*::
  Failure.
  Beat transmission failed.

== EXAMPLE

Send a single heartbeat to a _dmapi(1)_ process on localhost:

....
$ dmbeat -N dummy-node -H 127.0.0.1 -C 1 -V
....

== SEE ALSO

_dmapi(1)_

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
