= dmbot(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMBOT

== NAME

dmbot - XMPP chat bot for remote control of sensor nodes

== SYNOPSIS

*dmbot* --help

*dmbot* --version

*dmbot* --*node* _id_ --*jid* _jid_ --*password* _password_ --*host* _host_
[--*port* _port_] [--*tls*] [--*logger* _name_] [--*debug*] [--*verbose*]

*dmbot* --*config* _file_ [--*name* _name_]

== DESCRIPTION

This program is an XMPP bot that accepts commands via chat. Access to the bot is
limited to the JIDs added to table `group` in the configuration file. Requests
from clients whose JID is not in the table will be rejected. If table `group` is
empty, all clients are allowed to send commands to the bot.

All commands start with prefix `!`. For an overview, send chat command `!help`
to the bot. The bot understands the following commands:

!beats::
  Return current time of the sensor node in Swatch Internet Time.
!date::
  Return date and time of the sensor node in ISO 8601.
!help::
  Return help text.
!jid::
  Return full JID of bot.
!log <level> "<message>"::
  Send log message of given level to logger. The argument `level` must be a
  valid log level name or numeric log level. The argument `message` must be in
  quotes.
!node::
  Return node id of bot.
!poke::
  Return status message if bot is online.
!reconnect::
  Reconnect bot to server.
!uname::
  Return name and version of the operating system.
!uptime::
  Return uptime of the operating system
!version::
  Return bot version.

Passing the XMPP credentials via the command-line arguments `--jid` and
`--password` is insecure on multi-user operating systems and only recommended
for testing.

== OPTIONS

*--config*, *-c* _file_::
  Path to Lua-based configuration file.

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--help*, *-h*::
  Output available command-line arguments and quit.

*--host*, *-H* _host_::
  Domain of XMPP server.

*--jid*, *-J* _user_::
  Jabber id (JID) of the form `user@example.com`.

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of instance, XMPP resource, and table in given configuration file
  (default is `dmbot`).

*--node*, *-N* _id_::
  Sensor node id.

*--password*, *-P* _password_::
  JID password. Be aware that passing the credentials via command-line
  arguments is insecure and only recommended for testing.

*--port*, *-q* _port_::
  Port of XMPP server. The default port is 5222.

*--reconnect*, *-R*::
  Reconnect on error.

*--tls*, *-E*::
  Force TLS encryption.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Output version information and quit.

== EXIT STATUS

*0*::
  Success.
  Program executed without errors.

*1*::
  Failure.
  Program execution failed.

== EXAMPLE

Connect with JID `bot@example.com` to an XMPP server on port 5223 and wait for
commands:

....
$ dmbot --node dummy-node --jid bot@example.com --password secret \
  --host example.com --port 5223 --tls --verbose
....

If no configuration file is used, any client may send commands to the bot
without authorisation.

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
