= dmcamera(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMCAMERA

== NAME

dmcamera - captures images from webcam or IP camera

== SYNOPSIS

*dmcamera* --help

*dmcamera* --version

*dmcamera* --*node* _id_ --*sensor* _id_ --*target* _id_ --*directory* _path_
--*device* _name_ --*input* _path_ [--*interval* _n_] [--*mime* _name_]
[--*width* _n_] [--*height* _n_] [--*database* _file_] [--*logger* _name_]
[--*font* _name_] [--*fontsize* _n_] [--*debug*] [--*ipc*] [--*overlay*]
[--*verbose*]

*dmcamera* --*config* _file_ [--*name* _name_]

== DESCRIPTION

The *dmcamera* program captures images of an attached USB webcam (V4L2) or
remote IP camera (RTSP). The images are written to file in JPEG or PNG format.
If an image database is specified, the image meta data is added to the
database. The database can be created with _dminit(1)_. The program depends on
FFmpeg and GraphicsMagick. The executables _ffmpeg(1)_ and _gm(1)_ are required.

Optionally, a text overlay may be added to the image, containg the date and
time it was captured in ISO 8601. The overlay font must be known to
GraphicsMagick. For a list of all fonts supported by GraphicsMagick, run:

....
$ gm convert -list font
....

You may have to modify the GraphicsMagick configuration file `type.mgk`
according to the fonts installed on the system.

== OPTIONS

*--config*, *-c* _file_::
  Path to configuration file.

*--database*, *-d* _file_::
  Path to SQLite image database.

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--directory*, *-p* _path_::
  Directory to store the image files in.

*--device*, *-C* [rtsp|v4l2]::
  Camera device type (RTSP or V4L2).

*--font*, *-F* _name_::
  Name of font to use for overlay text. The font must be known to
  GraphicsMagick (default: DejaVuSansMono).

*--fontsize*, *-Z* _n_::
  Font size of overlay text (default: 12).

*--height*, *-H* _n_::
  Desired image height. May be ignored if unsupported by camera.

*--help*, *-h*::
  Print available command-line arguments and quit.

*--input*, *-i* _path_::
  URL of RTSP stream or path of V4L2 device (for example, `rtsp://localhost/` or
  `/dev/video0`).

*--interval*, *-I* _n_::
  Capture interval in seconds. By default, the interval is 0, which means that
  only a single image is captured.

*--ipc*, *-Q*::
  Uses a POSIX semaphore for process synchronisation. The name of the semaphore
  matches the instance name (with leading `/`). The semaphore is set to 1 each
  time an image has been captured. Only a single process shall wait for this
  semaphore, otherwise, reading occurs in round-robin fashion.

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--mime*, *-M* _name_::
  MIME type of image format to use, either `image/jpeg` or `image/png`.

*--name*, *-n* _name_::
  Name of program instance, configuration, and POSIX semaphore (default is
  `dmcamera`).

*--node*, *-N* _id_::
  Node id.

*--overlay*, *-O*::
  Add date and time in ISO 8601 as overlay text to image.

*--sensor*, *-S* _id_::
  Sensor id of camera.

*--target*, *-T* _id_::
  Target id of camera.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Print version information and quit.

*--width*, *-W* _n_::
  Desired image width. May be ignored if unsupported by camera.

== EXIT STATUS

*0*::
  Success.
  Program executed without errors.

*1*::
  Failure.
  Program execution failed.

== ENVIRONMENT

*NO_COLOR*::
  Disable ANSI colour output.

== EXAMPLE

Capture an image from an attached USB webcam (V4L2), write image to directory
`/tmp`, and add a text overlay with date and time in ISO 8601:

....
$ dmcamera -N dummy-node -S dummy-sensor -T dummy-target \
  -p /tmp -C v4l2 -i /dev/video0 -O -V
....

== SEE ALSO

_dminit(1)_, _dmupload(1)_
