= dmdbctl(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMDBCTL

== NAME

dmdbctl - command-line interface to DMPACK observation databases

== SYNOPSIS

*dmdbctl* --help

*dmdbctl* --version

*dmdbctl* --*database* _file_ --*id* _id_
[--*create*|--*read*|--*update*|--*delete* _type_] [--*name* _name_]
[--*meta* _meta_] [--*node* _id_] [--*type* _sensor_] [--*sn* _sn_]
[--*state* _n_] [--*x* _x_] [--*y* _y_] [--*z* _z_] [--*longitude* _lon_]
[--*latitude* _lat_] [--*elevation* _elev_] [--*verbose*]

== DESCRIPTION

The *dmdbctl* utility program performs create, read, update, or delete
operations on the observation database:

Create::
  Add nodes, sensors, and targets to the database.

Read::
  Read nodes, sensors, and targets from database. Print the records to standard
  output.

Update::
  Update nodes, sensors, and targets in the database.

Delete::
  Delete nodes, sensors, and targets from the database.

Only nodes, sensors, and targets are supported. All data attributes are passed
through command-line arguments.

== OPTIONS

*--create*, *-C* [node|sensor|target]::
  Create database record (node, sensor, or target).

*--database*, *-d* _file_::
  Path to SQLite observation database.

*--delete*, *-D* [node|sensor|target]::
  Delete database record (node, sensor, or target).

*--elevation*, *-E* _elev_::
  Elevation of node, sensor, or target in metres.

*--help*, *-h*::
  Print available command-line arguments and quit.

*--id*, *-I* _id_::
  ID of node, sensor, or target.

*--latitude*, *-L* _lat_::
  Latitude of node, sensor, or target in degrees (decimal).

*--longitude*, *-G* _lon_::
  Longitude node, sensor, or target in degrees (decimal).

*--meta*, *-M* _meta_::
  Meta description of node, sensor, or target.

*--name*, *-n* _name_::
  Name of node, sensor, or target.

*--node*, *-N* _id_::
  ID of the node the sensor is attached to.

*--read*, *-R* [node|sensor|target]::
  Read database record (node, sensor, or target).

*--sn*, *-Q* _sn_::
  Serial number of sensor.

*--state*, *-S* _n_::
  Target state.

*--type*, *-t* _sensor_::
  Sensor type, for example, `none`, `fs`, `process`, or `tps`.

*--update*, *-U* [node|sensor|target]::
  Update database record (node, sensor, or target).

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Print version information and quit.

*--x*, *-X* _x_::
  Node, sensor, or target x, usually in metres. May be in local or global
  coordinate system.

*--y*, *-Y* _z_::
  Node, sensor, or target z, usually in metres. May be in local or global
  coordinate system.

*--z*, *-Z* _z_::
  Node, sensor, or target z, usually in metres. May be in local or global
  coordinate system.

== EXIT STATUS

*0*::
  Success.
  Database operation finished without error.

*1*::
  Failure.
  Database operation failed.

== EXAMPLE

Add a new node of id `node-1` to the database:

....
$ dmdbctl -d observ.sqlite -C node -I node-1 -n "Node 1"
....

Delete target `target-1` from database:

....
$ dmdbctl -d observ.sqlite -D target -I target-1
....

Update the meta description of sensor `sensor-1`:

....
$ dmdbctl -d observ.sqlite -U sensor -I sensor-1 -M "in service"
....

== SEE ALSO

_dmdb(1)_, _dminit(1)_
