= dmdb(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMDB

== NAME

dmdb - stores observations received from message queue in database

== SYNOPSIS

*dmdb* --help

*dmdb* --version

*dmdb* --*database* _file_ --*node* _id_ [--*ipc*] [--*logger* _name_]
[--*debug*] [--*verbose*]

*dmdb* --*config* _file_ [--*name* _name_]

== DESCRIPTION

The *dmdb* program collects observations from a POSIX message queue and
stores them in a SQLite database. The name of the message queue matches the
given *dmdb* name, by default `dmdb`. The IPC option enables process
synchronisation via POSIX semaphores. The semaphore value is increased from 0
to 1 for every observation that has been received. The name of the semaphore
equals the *dmdb* name. Only a single process shall wait for the semaphore.

== OPTIONS

*--config*, *-c* _file_::
  Path to configuration file.

*--database*, *-d* _file_::
  Path to SQLite observation database.

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--help*, *-h*::
  Output available command-line arguments and quit.

*--ipc*, *-Q*::
  Uses a POSIX semaphore for process synchronisation. The name of the semaphore
  matches the instance name (with leading `/`). The semaphore is set to 1 each
  time an observation has been received. Only a single process shall wait for
  this semaphore, otherwise, reading occurs in round-robin fashion.

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of program instance, configuration, POSIX message queue, and POSIX
  semaphore (default is `dmdb`).

*--node*, *-N* _id_::
  Node id.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Output version information and quit.

== EXIT STATUS

*0*::
  Success.
  Program executed without errors.

*1*::
  Failure.
  Program execution failed.

== EXAMPLE

Create a message queue `dmdb`, wait for incoming observations, and store them
in the given database:

....
$ dmdb --name dmdb --node dummy-node --database /var/dmpack/observ.sqlite --verbose
....

== SEE ALSO

_dmdbctl(1)_, _dmsync(1)_

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
