= dmdbctl(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMDBCTL

== NAME

dmdbctl - command-line interface to DMPACK observation databases

== SYNOPSIS

*dmdbctl* --help

*dmdbctl* --version

*dmdbctl* --*database* _file_ --*id* _id_ [--*create* _type_] [--*read* _type_]
[--*update* _type_] [--*delete* _type_] [--*name* _name_] [--*meta* _meta_]
[--*node* _id_] [--*type* _sensor_] [--*sn* _sn_] [--*state* _n_]
[--*easting* _x_] [--*northing* _y_] [--*altitude* _z_] [--*verbose*]

== DESCRIPTION

The *dmdbctl* utility program performs create, read, update, or delete
operations on the observation databasae. Only nodes, sensors, and targets are
supported. Data attributes are passed through command-line arguments.

== OPTIONS

*--altitude*, *-Z* _z_::
  Node, sensor, or target z, usually in metres. May be in local or global
  coordinate system.

*--create*, *-C* [node|sensor|target]::
  Create database record (node, sensor, or target).

*--database*, *-d* _file_::
  Path to SQLite observation database.

*--delete*, *-D* [node|sensor|target]::
  Delete database record (node, sensor, or target).

*--easting*, *-X* _x_::
  Node, sensor, or target x, usually in metres. May be in local or global
  coordinate system.

*--help*, *-h*::
  Output available command-line arguments and quit.

*--id*, *-I* _id_::
  ID of node, sensor, or target.

*--meta*, *-M* _meta_::
  Meta description of node, sensor, or target.

*--name*, *-n* _name_::
  Name of node, sensor, or target.

*--node*, *-N* _id_::
  ID of the node the sensor is attached to.

*--northing*, *-Y* _y_::
  Node, sensor, or target y, usually in metres. May be in local or global
  coordinate system.

*--read*, *-R* [node|sensor|target]::
  Read database record (node, sensor, or target).

*--sn*, *-Q* _sn_::
  Serial number of sensor.

*--state*, *-S* _n_::
  Target state.

*--type*, *-t* _sensor_::
  Sensor type, for example, `none`, `fs`, `process`, or `tps`.

*--update*, *-U* [node|sensor|target]::
  Update database record (node, sensor, or target).

*--verbose*, *-V*::
  Print additional log messages to _stderr_.

*--version*, *-v*::
  Output version information and quit.

== EXIT STATUS

*0*::
  Success.
  Database operation finished without error.

*1*::
  Failure.
  Database operation failed.

== EXAMPLE

Add a new node of id `dummy-node` to the database:

....
$ dmdbctl --database observ.sqlite --create node --id dummy-node --name "Dummy Node"
....

Delete target `dummy-target` from database:

....
$ dmdbctl --database observ.sqlite --delete target --id dummy-target
....

Update the meta description of sensor `dummy-sensor`:

....
$ dmdbctl --database observ.sqlite --update sensor --id dummy-sensor --meta "in service"
....

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2023 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
