= dminit(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMINIT

== NAME

dminit - initialises DMPACK databases

== SYNOPSIS

*dminit* --help

*dminit* --version

*dminit* --*type* _type_ --*database* _file_ [--*force*] [--*sync*] [--*wal*]

== DESCRIPTION

The *dminit* utility program creates beat, log, and observation databases. No
action is performed if the specified database already exists, unless
command-line argument `--force` is passed.

A synchronisation table is required for observation and log synchronisation with
an RPC server. The argument may be omitted if this functionality is not used.

Write-Ahead Logging (WAL) should be enabled for databases with multiple
readers.

== OPTIONS

*--database*, *-d* _file_::
  File path of the new SQLite database.

*--force*, *-F*::
  Force creation of tables even if the database already exists.

*--help*, *-h*::
  Output available command-line arguments and quit.

*--sync*, *-Y*::
  Add synchronisation tables. Enable for data synchronisation between client
  and server.

*--type*, *-t* [beat|log|observ]::
  Type of database, either beat, log, or observation.

*--version*, *-v*::
  Output version information and quit.

*--wal*, *-W*::
  Enable Write-Ahead Logging.

== EXIT STATUS

*0*::
  Success.
  Database was created.

*1*::
  Failure.
  Database creation failed.

== EXAMPLE

Create a beat database:

....
$ dminit --type beat --database beat.sqlite --wal
....

Create a log database with remote synchronisation tables:

....
$ dminit --type log --database log.sqlite --sync --wal
....

Create an observation database with remote synchronisation tables:

....
$ dminit --type observ --database observ.sqlite --sync --wal
....

== SEE ALSO

_dmbackup(1)_, _dmsync(1)_

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2024 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
