= dmlog(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMLOG

== NAME

dmlog - sends log to POSIX message queue

== SYNOPSIS

*dmlog* --help

*dmlog* --version

*dmlog* --*node* _id_ --*message* _string_ [--*logger* _name_] [--*level* _n_]
[--*error* _n_] [--*node* _id_] [--*sensor* _id_] [--*target* _id_]
[--*observ* _id_] [--*source* _source_] [--*verbose*]

== DESCRIPTION

The *dmlog* utility forwards a log message to the POSIX message queue of a
_dmlogger(1)_ instance. Argument `--message` is mandatory. Pass the name of
the _dmlogger_ or _dmrecv_ instance to send the log to through command-line
argument `--logger`. Alternatively, set environment variable `DMLOGGER` to the
name of the logger. The command-line argument overwrites the environment
variable. The default log level is `info` (2). Valid log levels are `debug`
(1), `info` (2), `warning` (3), `error` (4), `critical` (5), and `user` (6).
The program terminates after log transmission.

== OPTIONS

*--error*, *-e* _n_::
  DMPACK error code (>= 0).

*--help*, *-h*::
  Print available command-line arguments and quit.

*--level*, *-L* _level_::
  Log level, from `debug` (1) to `user` (6) The default level is `info` (2).
  The argument may be an integer or log level name string.

*--logger*, *-l* _name_::
  Name of logger instance and POSIX message queue. If the command-line argument
  is not passed and the environment variable `DMLOGGER` is not set, the log
  messages will not be transmitted via POSIX message queue.

*--message*, *-m* _string_::
  Log message (max. 512 characters).

*--node*, *-N* _id_::
  Node id.

*--observ*, *-O* _id_::
  Observation id (UUIDv4).

*--sensor*, *-S* _id_::
  Sensor id.

*--source*, *-Z* _source_::
  Name of log message source (sender).

*--target*, *-T* _id_::
  Target id.

*--verbose*, *-V*::
  Print log to _stderr_.

*--version*, *-v*::
  Print version information and quit.

== EXIT STATUS

*0*::
  Success.
  Log has been sent.

*1*::
  Failure.
  Program execution failed.

== EXAMPLE

Send a log message to the POSIX message queue of logger `dmlogger`:

....
$ dmlog --node dummy-node --level warning --message "low battery" --source test --verbose
2022-12-09T22:50:44.161000+01:00 [WARNING ] test - low battery
....

The logger will receive the log message and insert it into the log database (if
the log level is greater or equal the minimum log level):

....
$ dmlogger --node dummy-node --database log.sqlite --verbose
2022-12-09T22:50:44.161000+01:00 [WARNING] test - low battery
....

== SEE ALSO

_dmlogger(1)_

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
