= dmmb(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMMB

== NAME

dmmb - reads observations from Modbus RTU/TCP device

== SYNOPSIS

*dmmb* --help

*dmmb* --version

*dmmb* --*config* _file_ [--*name* _name_] [--*node* _id_] [--*sensor* _id_]
[--*logger* _name_] [--*format* _name_] [--*output* _file_] [--*mqueue*]
[--*debug*] [--*verbose*]

== DESCRIPTION

The *dmmb* program reads values from or writes values to Modbus RTU/TCP
registers by sequentially processing the job list loaded from a configuration
file. Each request of an observation must contain the Modbus register parameters
in the request string. The value of the first response is set to the result of
the read operation. Up to 8 requests to read and/or write values are permitted.
Integers read from a register may be scaled using an optional scale denominator.

For example, to read a 2-byte unsigned integer from holding register 40050 of
slave device 1 with a scale factor of 1/10, the attribute `request` of a request
must be set to:

....
access=read, slave=1, address=40050, type=uint16, scale=10
....

Or, to read a 4-byte floating-point value in ABCD byte order from register
40060:

....
access=read, slave=1, address=40060, type=float, order=abcd
....

Only integer values may be written to an input register, for instance:

....
access=write, slave=1, address=30010, type=uint16, value=1
....

The value is converted to `uint16` automatically. The command string can be in
lower or upper case. White spaces will be ignored.

Observations will be forwarded to the next receiver via POSIX message queue if
any receiver is specified. The program can act as a sole data logger if output
and format are set. If the output path is set to `-`, observations are printed
to _stdout_, else to file.

A configuration file is required to configure the jobs to perform. Each
observation must have a valid target id. The database must contain the specified
node, sensor, and targets.

== OPTIONS

*--config*, *-c* _file_::
  File path to the configuration file.

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--format*, *-f* [csv|jsonl]::
  Output format of observations if `--output` is set. Either CSV or JSON Lines.

*--help*, *-h*::
  Print available command-line arguments and quit.

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of program instance, configuration, and message queue (default is `dmmb`).

*--mqueue*, *-Q*::
  Create message queue to receive observations from.

*--node*, *-N* _id_::
  Node id.

*--output*, *-o* _file_::
  Output file to append observations to (`-` for _stdout_).

*--sensor*, *-S* _id_::
  Sensor id.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Print version information and quit.

== EXIT STATUS

*0*::
  Success.
  Process terminated without errors.

*1*::
  Failure.
  Process failed.

== EXAMPLE

Read the jobs to perform from configuration file and execute them sequentially:

....
$ dmmb --name dmmb --config /usr/local/etc/dmpack/dmmb.conf --verbose
....

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
