= dmrecv(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMRECV

== NAME

dmrecv - receives observations and logs from POSIX message queue

== SYNOPSIS

*dmrecv* --help

*dmrecv* --version

*dmrecv* --*type* [log|observ] --*format* [block|csv|jsonl|nml]
[--*name* _name_] [--*output* _file_] [--*response* _name_] [--*node* _id_]
[--*logger* _name_] [--*forward*] [--*replace*] [--*verbose*]

*dmrecv* --*config* _file_ [--*name* _name_]

== DESCRIPTION

The *dmrecv* program listens to the POSIX message queue of its name and writes
received observations and logs to _stdout_, file, or named pipe; in ASCII block,
CSV, JSON, or Fortran 95 Namelist format. By default, the serialised data is
appended to the end of the output file. If argument `--replace` is passed, the
file will be replaced consecutively.

Received observations are not forwarded to the next specified receiver, unless
argument `--forward` is set. If no receivers are defined or left, the
observation will be discarded after output.

The output format `block` is available for observation data only, and requires
a valid response name. Received observations will be searched for this response
and converted to data point type if found. The data point is printed in ASCII
block format.

If output format JSON Lines is selected, observations and logs are written
sequentially as JSON objects to file or _stdout_, separated by new line. Use
_jq(1)_ to convert a file `input.jsonl` of JSON objects to a JSON array in
`output.json`:

....
$ jq -s '.' input.jsonl > output.json
....

The program settings are passed through command-line arguments or an optional
configuration file. The arguments overwrite settings from file.

== OPTIONS

*--config*, *-c* _file_::
  Path to configuration file.

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--format*, *-f* [block|csv|jsonl|nml]::
  Output format, either ASCII block, CSV, JSON Lines, or Namelist. Format
  `block` is allowed for type `observ` only.

*--forward*, *-F*::
  Forward each observation to its next specified receiver.

*--help*, *-h*::
  Print available command-line arguments and quit.

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of configuration and POSIX message queue (default is `dmrecv`).

*--node*, *-N* _id_::
  Optional node id.

*--output*, *-o* _file_::
  Path of output file. Prints serialised data to _stdout_ if `-` or not set.

*--replace*, *-r*::
  Replace output file instead of appending data.

*--response*, *-R* _name_::
  Name of the observation response to output (required for format `block`).

*--type*, *-t* [log|observ]::
  Data type to receive, either log or observation.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Print version information and quit.

== EXIT STATUS

*0*::
  Success.
  Program terminated normally.

*1*::
  Failure.
  Program execution failed.

== ENVIRONMENT

*NO_COLOR*::
  Disable ANSI colour output.

== EXAMPLE

Write received log messages in CSV format to file `/tmp/logs.csv`:

....
$ dmrecv -n dmrecv -t log -f csv -o /tmp/logs.csv
....

Output observations in JSON format to _stdout_:

....
$ dmrecv -n dmrecv -t observ -f json
....

Output observation responses of name `x` in ASCII block format to _stdout_:

....
$ dmrecv -n dmrecv -t observ -f block -R x
....

== SEE ALSO

_dmsend(1)_
