= dmserial(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMSERIAL

== NAME

dmserial - reads observations from TTY/PTY

== SYNOPSIS

*dmserial* --help

*dmserial* --version

*dmserial* --*config* _file_ [--*name* _name_] [--*node* _id_] [--*sensor* _id_]
[--*logger* _name_] [--*tty* _path_] [--*baudrate* _n_] [--*bytesize* _n_]
[--*stopbits* _n_] [--*parity* _name_] [--*timeout* _n_] [--*format* _name_]
[--*output* _file_] [--*dtr*] [--*rts*] [--*debug*] [--*verbose*]

== DESCRIPTION

The *dmserial* program sends requests to a sensor connected via
USB/RS-232/RS-422/RS-485. Sensor commands and responses are sent/received
through a teletype (TTY) device provided by the operating system. A
pseudo-terminal (PTY) may be used to connect a virtual sensor.

Each request of an observation must contain the raw request intended for the
sensor in attribute `request`. Response values are extracted by group from the
raw response using the given regular expression pattern. Each group name must
match a response name. Response names are limited to eight characters.

Observations will be forwarded to the next receiver via POSIX message queue if
any receiver is specified. The program can act as a sole data logger if output
and format are set. If the output path is set to `-`, observations are printed
to _stdout_, else to file.

A configuration file is required to configure the jobs to perform. Each
observation must have a valid target id. The database must contain the specified
node, sensor, and targets. The observation requests may be created by using
GeoCOM API functions.

== OPTIONS

*--baudrate*, *-B* _n_::
  Number of symbols transmitted per second. The following baud rates are
  supported: 50, 75, 110, 134, 150, 200, 300, 600, 1200, 1800, 2400, 4800, 9600,
  19200, 38400, 57600, 115200, 230400, 460800, 921600.

*--bytesize*, *-Z* _n_::
  Byte size (5, 6, 7, 8).

*--config*, *-c* _file_::
  File path to the configuration file.

*--debug*, *-D*::
  Forward logs messages of level `LVL_DEBUG` via IPC (if logger is set).

*--dtr*, *-Q*::
  Enable Data Terminal Ready (DTR).

*--format*, *-f* [csv|jsonl]::
  Output format of observations if `--output` is set. Either CSV or JSON Lines.

*--help*, *-h*::
  Output available command-line arguments and quit.

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of program instance and configuration (default is `dmserial`).

*--node*, *-N* _id_::
  Node id.

*--output*, *-o* _file_::
  Output file to append observations to (`-` for _stdout_).

*--parity*, *-P* [none|even|odd]::
  Parity bits (`none`, `even`, or `odd`).

*--rts*, *-R*::
  Enable Request To Send (RTS).

*--sensor*, *-S* _id_::
  Sensor id.

*--stopbits*, *-O* _n_::
  Number of stop bits (1, 2).

*--timeout*, *-T* _n_::
  Connection timeout in seconds.

*--tty*, *-Y* _path_::
  Path to TTY/PTY device (for example, `/dev/ttyU0`).

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Output version information and quit.

== EXIT STATUS

*0*::
  Success.
  Process terminated without errors.

*1*::
  Failure.
  Process failed.

== EXAMPLE

Read the jobs to perform from configuration file and execute them sequentially:

....
$ dmserial --name dmserial --config /usr/local/etc/dmpack/dmserial.conf --verbose
....

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2024 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
