= dmuuid(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMUUID

== NAME

dmuuid - generates pseudo-random UUIDs

== SYNOPSIS

*dmuuid* --help

*dmuuid* --version

*dmuuid* [--*count* _n_] [--*hyphens*]

*dmuuid* --*convert* < _file_

== DESCRIPTION

The *dmuuid* program generates pseudo-random UUIDs. By default, DMPACK uses 32
characters long UUIDv4 identifers in hexadecimal format (without hyphens). If
command-line flag `--hyphens` is set, 36 characters long identifiers with
hyphens are returned. The option `--convert` expects UUIDs to be passed via
standard input. Invalid identifiers will be replaced with the default UUIDv4.

== OPTIONS

*--convert*, *-C*::
  Add hyphens to hexadecimal UUIDs passed via _stdin_.

*--count*, *-n* _n_::
  Number of UUIDs to generate (default: 1).

*--help*, *-h*::
  Output available command-line arguments and quit.

*--hyphens*, *-H*::
  Return 36 characters long UUIDs with hyphens.

*--version*, *-v*::
  Output version information and quit.

== EXIT STATUS

*0*::
  Success.
  UUID generation was successful.

*1*::
  Failure.
  UUID generation failed.

== EXAMPLE

Create three random identifiers:

....
$ dmuuid --count 3
6827049760c545ad80d4082cc50203e8
ad488d0b8edd4c6c94582e702a810ada
3d3eee7ae1fb4259b5df72f854aaa369
....

Add hyphens to a hexadecimal UUIDv4:

....
$ echo "3d3eee7ae1fb4259b5df72f854aaa369" | dmuuid --convert
3d3eee7a-e1fb-4259-b5df-72f854aaa369
....

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
