= dmved(1)
Philipp Engel
v1.0.0
:doctype: manpage
:manmanual: User Commands
:mansource: DMVED

== NAME

dmved - reads status of connected Victron Energy MPPT charger

== SYNOPSIS

*dmved* --help

*dmved* --version

*dmved* --*config* _file_ [--*name* _name_] [--*node* _id_] [--*sensor* _id_]
[--*target* _id_] [--*logger* _name_] [--*path* _path_] [--*receiver* _name_]
[--*interval* _seconds_] [--*debug*] [--*verbose*]

== DESCRIPTION

This program captures status data received from a connected Maximum Power Point
Tracking (MPPT) charger by Victron Energy, using the VE.Direct protocol. Only
the BlueSolar and SmartSolar MPPT series are currently supported. The serial
port will be configured to 19200 baud (8N1). Observations are sent to the
receiver via message queue in the specified interval.

The following 16 VE.Direct fields are captured:

CS::   State of operation.
ERR::  Error code.
H19::  Yield total (kWh/100).
H20::  Yield today (kWh/100).
H21::  Maximum power today (W).
H22::  Yield yesterday (kWh/100).
H23::  Maximum power yesterday (W).
HSDS:: Day sequence number (0 to 364).
I::    Main or channel 1 battery current (mA).
IL::   Load current (mA).
LOAD:: Load output state (on or off).
MPPT:: Tracker operation mode.
OR::   Off-state reason.
PPV::  Panel power (W).
V::    Main or channel 1 (battery) voltage (mV).
VPV::  Panel voltage (mV).

== OPTIONS

*--config*, *-c* _file_::
  File path to the configuration file.

*--debug*, *-D*::
  Forward logs messages of level `LL_DEBUG` via IPC (if logger is set).

*--help*, *-h*::
  Output available command-line arguments and quit.

*--interval*, *-I* _seconds_::
  Observation emit interval in seconds (default is 60 seconds).

*--logger*, *-l* _name_::
  Name of logger. If set, sends logs to _dmlogger(1)_ process of given name.

*--name*, *-n* _name_::
  Name of program instance and configuration (default is `dmved`).

*--node*, *-N* _id_::
  Node id.

*--path*, *-p* _path_::
  Path to TTY device (for example, `/dev/ttyUSB0`).

*--receiver*, *-r* _name_::
  Name of the observation receiver, without leading `/`.

*--sensor*, *-S* _id_::
  Sensor id.

*--target*, *-T* _id_::
  Target id.

*--verbose*, *-V*::
  Print log messages to _stderr_.

*--version*, *-v*::
  Output version information and quit.

== EXIT STATUS

*0*::
  Success.
  Process terminated without errors.

*1*::
  Failure.
  Process failed.

== EXAMPLE

Read status data from MPPT connected via TTL:

....
$ dmved --name dmved --config /usr/local/etc/dmpack/dmved.conf --verbose
....

== RESOURCES

*Project web site:* https://www.dabamos.de/

== COPYING

Copyright (C) 2025 {author}. +
Free use of this software is granted under the terms of the ISC Licence.
